### ISSUE TITLE
How to trigger get message after send message?

### ISSUE THREAD

**Issue by vishal0909** [fantakim/Sendbird#10]
Hello @fantakim 
How to get message after send message?
How can I do the trigger for get message?

**Comment by fantakim** [comment]
>  How to get message after send message?

You can receive the object of the sent message as below.
```c#
var message = await _messageService.SendMessageAsync(channel, new AdminMessageOptions { Message = "welcome.." });
```

> How can I do the trigger for get message?

This project implements some of the [Platform API](https://sendbird.com/docs/chat/v3/platform-api/overview) functions used in the backend.
Platform APIs do not have real-time event handling features.

**Comment by vishal0909** [comment]
Hello @fantakim 
Thank you for your response.
How can I achive thgis things. I am using your API and I already done with my requirement.
Now I am stuck in here. Can you please help me todo this things.

**Comment by fantakim** [comment]
@vishal0909  
Using [Sendbird UIKit](https://sendbird.com/docs/uikit) would be convenient for implementing a chat client app.
this project is not related to a client app.
