### ISSUE TITLE
I am passing user ids, but still gettting an error. "is_distinct. If you want this value to be set "true", user_ids must be required.".

### ISSUE THREAD

**Issue by vishal0909** [fantakim/Sendbird#9]

**Comment by fantakim** [comment]
@vishal0909 
When creating a group channel, refer to the articles below.
https://sendbird.com/docs/chat/v3/platform-api/channel/creating-a-channel/create-a-group-channel

And see the link below for the test code.
https://github.com/fantakim/Sendbird/blob/main/SendbirdTests/FullScenarioTest.cs

**Comment by vishal0909** [comment]
Hello @fantakim 
Good Morning

I find the bug. If you want to distinct channel, you have user your Dashboard.
Without user you can't create channel.
